#!/bin/sh

# Create modem interface
uci -q set network.modem=interface
uci -q set network.modem.proto='modemmanager'
uci -q set network.modem.device='qcom-soc'
uci -q set network.modem.auth='none'
uci -q set network.modem.apn='internet'
uci -q set network.modem.allowedmode='4g|3g'
uci -q set network.modem.preferredmode='4g'
uci -q set network.modem.ifname='wwan0'
uci -q del_list firewall.@zone[1].network='modem'
uci -q add_list firewall.@zone[1].network='modem'

# We don't have eth0
uci -q del_list "network.@device[0].ports=eth0" 2>/dev/null || true
if [ -f /etc/board.json ]; then
	sed -i 's/"device": "eth0"/"device": "br-lan"/g' /etc/board.json
fi

# Remove target-specific APK feed (msm89xx is not on downloads.openwrt.org)
sed -i '\|/targets/msm89xx/msm8916/packages|d' /etc/apk/repositories.d/distfeeds.list 2>/dev/null || true

uci -q commit
